FROM ruby:3.2.2-slim

RUN apt-get update -qq \
  && apt-get install --no-install-recommends -y build-essential curl git libpq-dev ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_JOBS=4 \
    RAILS_LOG_TO_STDOUT=true

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000
