default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: salarymanagement_development

test:
  <<: *default
  database: salarymanagement_test

production:
  primary: &primary_production
    <<: *default
    database: salarymanagement_production
    username: salarymanagement
    password: <%= ENV["SALARYMANAGEMENT_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: salarymanagement_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: salarymanagement_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: salarymanagement_production_cable
    migrations_paths: db/cable_migrate
